<?xml version="1.0"?>

<robot name="maggie" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- MATERIALS -->

    <xacro:include filename="$(find maggie_description)/urdf/materials.urdf.xacro" />

    <!-- CONSTANTS & COMMON MACROS -->

    <xacro:include filename="$(find maggie_description)/urdf/common.xacro" />

    <!-- BODY -->

    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${baselen/2+0.05}" />
            
            <geometry>
                <cylinder length="${baselen}" radius="0.2" />
            </geometry>

            <material name="white" />
        </visual>

        <collision>
            <geometry>
                <cylinder length="${baselen}" radius="0.2" />
            </geometry>
        </collision>

        <xacro:default_inertial mass="20" />
    </link>

    <link name="upper_base_link">
        <visual>
            <geometry>
                <cylinder length="${bodylen}" radius="0.2" />
            </geometry>

            <material name="blue" />
        </visual>

        <collision>
            <geometry>
                <cylinder length="${bodylen}" radius="0.2" />
            </geometry>
        </collision>

        <xacro:default_inertial mass="20" />
    </link>

    <joint name="base_to_upper_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="upper_base_link" />

        <origin xyz="0 0 ${(baselen+0.05)+bodylen/2}" />
    </joint>
    
    <!-- NECK -->

    <link name="neck_link">
        <visual>
            <geometry>
                <cylinder length="0.05" radius="0.04" />
            </geometry>

            <material name="black" />
        </visual>

        <collision>
            <geometry>
                <cylinder length="0.05" radius="0.02" />
            </geometry>
        </collision>

        <xacro:default_inertial mass="0.2" />
    </link>
    
    <joint name="base_to_neck_joint" type="fixed">
        <parent link="upper_base_link" />
        <child link="neck_link" />

        <origin xyz="0 0 ${bodylen/2+0.05/2}" />
    </joint>

    <!-- HEAD -->
    
    <link name="link_virtual" />

    <joint name="neck_to_pan_head_joint" type="revolute">
        <parent link="neck_link" />
        <child link="link_virtual" />

        <origin xyz="0 0 ${headlen/2}" />
        <axis xyz="0 0 1" />
        <limit effort="1000.0" lower="-${pi/2}" upper="${pi/2}" velocity="${defaultvel}" />
    </joint>

    <link name="head_link">
        <visual>
            <geometry>
                <sphere radius="${headlen/2}" />
            </geometry>

            <material name="white" />
        </visual>

        <collision>
            <geometry>
                <sphere radius="${headlen/2}" />
            </geometry>
        </collision>

        <xacro:default_inertial mass="5" />
    </link>

    <joint name="base_to_tilt_head_joint" type="revolute">
        <parent link="link_virtual" />
        <child link="head_link" />

        <origin xyz="0 0 0" />
        <axis xyz="1 0 0" />
        <limit effort="1000.0" lower="-0.26" upper="0.26" velocity="${defaultvel}" />
    </joint>

    <!-- MOUTH -->

    <link name="mouth_link">
        <visual>
            <geometry>
                <box size="0.1 0.02 0.02" />
            </geometry>

            <material name="black" />
        </visual>

        <collision>
            <geometry>
                <box size="0.1 0.02 0.02" />
            </geometry>
        </collision>

        <xacro:default_inertial mass="0.02" />
    </link>

    <joint name="head_to_mouth_joint" type="fixed">
        <parent link="head_link" />
        <child link="mouth_link" />

        <origin xyz="0 0.17 -0.1" />
    </joint>

    <!-- EYES -->

    <xacro:include filename="$(find maggie_description)/urdf/eyes.urdf.xacro" />

    <xacro:eye prefix="left" reflect="-1" />
    <xacro:eye prefix="right" reflect="1" />

    <!-- ARMS -->

    <xacro:include filename="$(find maggie_description)/urdf/arms.urdf.xacro" />

    <xacro:arm prefix="left" reflect="-1" />
    <xacro:arm prefix="right" reflect="1" />

    <!-- SCREEN -->

    <link name="screen_link">
        <visual>
            <geometry>
                <box size="0.16 0.02 0.21" />
            </geometry>

            <material name="black" />
        </visual>

        <collision>
            <geometry>
                <box size="0.16 0.02 0.21" />
            </geometry>
        </collision>

        <xacro:default_inertial mass="2" />
    </link>

    <joint name="base_to_screen_joint" type="fixed">
        <parent link="upper_base_link" />
        <child link="screen_link" />

        <origin xyz="0 0.19 ${0.21/2}" />
    </joint>

    <!-- WHEELS -->

    <xacro:include filename="$(find maggie_description)/urdf/wheels.urdf.xacro" />

    <xacro:wheel prefix="left" reflect="-1" />
    <xacro:wheel prefix="right" reflect="1" />

    <!-- RFID -->

    <link name="rfid_link">
        <xacro:default_inertial mass="0.02" />
    </link>

    <joint name="head_to_rfid_joint" type="fixed">
        <parent link="head_link" />
        <child link="rfid_link" />

        <origin xyz="0 0.2 0" rpy="0 0 0" />
    </joint>

    <!-- IR CONTROLLER -->

    <link name="ir_link">
        <xacro:default_inertial mass="0.02" />
    </link>

    <joint name="base_to_ir_joint" type="fixed">
        <parent link="base_link" />
        <child link="ir_link" />

        <origin xyz="0 0.2 ${baselen/2+0.05+0.3}" rpy="0 0 0" />
    </joint>

    <!-- LASERS -->

    <link name="sick_link">
        <xacro:default_inertial mass="5" />
    </link>

    <joint name="base_to_sick_joint" type="fixed">
        <parent link="base_link" />
        <child link="sick_link" />

        <origin xyz="0 0.2 ${baselen/2+0.05}" rpy="0 0 0" />
    </joint>

    <link name="hokuyo_link">
        <xacro:default_inertial mass="1" />
    </link>

    <joint name="base_to_hokuyo_joint" type="fixed">
        <parent link="base_link" />
        <child link="hokuyo_link" />

        <origin xyz="0 -0.2 ${baselen/2+0.05+0.2}" rpy="0 0 -${pi}" />
    </joint>

    <!-- TOUCH SENSORS -->

    <link name="touch_head_link">
        <xacro:default_inertial mass="0.01" />
    </link>

    <joint name="head_to_touch_head_joint" type="fixed">
        <parent link="head_link" />
        <child link="touch_head_link" />

        <origin xyz="0 0 0.2" rpy="0 0 0" />
    </joint>

    <xacro:include filename="$(find maggie_description)/urdf/touch_back.urdf.xacro" />

    <xacro:touch_back prefix="left" reflect="-1" />
    <xacro:touch_back prefix="right" reflect="1" />

    <xacro:include filename="$(find maggie_description)/urdf/touch_shoulders.urdf.xacro" />

    <xacro:touch_shoulder prefix="left" reflect="-1" />
    <xacro:touch_shoulder prefix="right" reflect="1" />

    <xacro:include filename="$(find maggie_description)/urdf/touch_hands.urdf.xacro" />

    <xacro:touch_hand prefix="left" reflect="-1" />
    <xacro:touch_hand prefix="right" reflect="1" />

    <!-- CAMERAS -->

    <link name="kinect_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi/2}" />

            <geometry>
                <mesh filename="package://maggie_description/meshes/kinect/kinect.dae" scale="0.001 0.001 0.001" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 ${pi/2}" />

            <geometry>
                <mesh filename="package://maggie_description/meshes/kinect/kinect.dae" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>

        <xacro:default_inertial mass="2" />
    </link>

    <joint name="base_to_kinect_joint" type="fixed">
        <parent link="base_link" />
        <child link="kinect_link" />

        <origin xyz="0 ${baselen/2+0.05} ${baselen+0.05+0.02}" rpy="0 0 0" />
    </joint>

    <link name="webcam_link">
        <xacro:default_inertial mass="0.03" />
    </link>

    <joint name="mouth_to_webcam_joint" type="fixed">
        <parent link="mouth_link" />
        <child link="webcam_link" />

        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>
</robot>
