<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="arm" params="prefix reflect">
        <link name="${prefix}_arm_link">
            <visual>
                <origin xyz="0 0 ${-armlen/2}" rpy="0 ${pi/2} ${pi/2}" />

                <geometry>
                    <box size="${armlen} 0.15 0.1" />
                </geometry>

                <material name="white" />
            </visual>

            <collision>
                <origin xyz="0 0 -0.2" rpy="0 ${pi/2} 0" />

                <geometry>
                    <box size="${armlen} 0.15 0.1" />
                </geometry>
            </collision>

            <xacro:default_inertial mass="1" />
        </link>

        <joint name="base_to_${prefix}_arm_joint" type="revolute">
            <parent link="upper_base_link" />
            <child link="${prefix}_arm_link" />

            <origin xyz="0 ${reflect*0.25} ${bodylen/2}" />
            <axis xyz="1 0 0" />
            <limit effort="1000.0" lower="-${pi/3}" upper="${3*pi/4}" velocity="${defaultvel}" />
        </joint>
    </xacro:macro>
</robot>
